name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: classic
          base: header, activity, metadata
          repositories_affiliations: ""
          commits_authoring: tahmidul612, Tahmidul Islam, thelittolprince
          config_timezone: America/Toronto
          output_condition: data-changed
          token: ${{ secrets.METRICS_TOKEN }}
          use_prebuilt_image: yes
          optimize: svg
          experimental_features: --optimize-svg
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
